// @vitest-environment jsdom

import { act } from "react";
import { createRoot } from "react-dom/client";
import type { IssueWorkProduct } from "@paperclipai/shared";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { IssueWorkProductsSection } from "./IssueWorkProductsSection";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
(globalThis as any).IS_REACT_ACT_ENVIRONMENT = true;

function createWorkProduct(overrides: Partial<IssueWorkProduct> = {}): IssueWorkProduct {
  return {
    id: "work-product-1",
    companyId: "company-1",
    projectId: null,
    issueId: "issue-1",
    executionWorkspaceId: null,
    runtimeServiceId: null,
    type: "preview_url",
    provider: "vercel",
    externalId: "preview-1",
    title: "Preview deployment",
    url: "https://paperclip-preview.vercel.app/issues/PAP-1",
    status: "active",
    reviewState: "none",
    isPrimary: true,
    healthStatus: "healthy",
    summary: "Live preview generated by the issue run.",
    metadata: null,
    createdByRunId: null,
    createdAt: new Date("2026-04-20T12:00:00.000Z"),
    updatedAt: new Date("2026-04-20T12:00:00.000Z"),
    ...overrides,
  };
}

describe("IssueWorkProductsSection", () => {
  let container: HTMLDivElement;

  beforeEach(() => {
    container = document.createElement("div");
    document.body.appendChild(container);
  });

  afterEach(() => {
    container.remove();
  });

  it("renders visible links and provider labels for Vercel and Cloudinary work products", () => {
    const root = createRoot(container);

    act(() => {
      root.render(
        <IssueWorkProductsSection
          workProducts={[
            createWorkProduct(),
            createWorkProduct({
              id: "work-product-2",
              type: "artifact",
              provider: "cloudinary",
              title: "Generated thumbnail",
              url: "https://res.cloudinary.com/demo/image/upload/sample.png",
              status: "ready_for_review",
              isPrimary: false,
              healthStatus: "unknown",
              summary: "Thumbnail uploaded during the artifact read-back check.",
            }),
          ]}
        />,
      );
    });

    expect(container.textContent).toContain("Work products");
    expect(container.textContent).toContain("2");
    expect(container.textContent).toContain("Preview deployment");
    expect(container.textContent).toContain("Vercel");
    expect(container.textContent).toContain("Active");
    expect(container.textContent).toContain("Primary");
    expect(container.textContent).toContain("Healthy");
    expect(container.textContent).toContain("paperclip-preview.vercel.app");
    expect(container.textContent).toContain("Generated thumbnail");
    expect(container.textContent).toContain("Cloudinary");
    expect(container.textContent).toContain("Ready For Review");
    expect(container.textContent).toContain("res.cloudinary.com");

    const links = Array.from(container.querySelectorAll<HTMLAnchorElement>("[data-testid='issue-work-product']"));
    expect(links).toHaveLength(2);
    expect(links[0]?.href).toBe("https://paperclip-preview.vercel.app/issues/PAP-1");
    expect(links[1]?.href).toBe("https://res.cloudinary.com/demo/image/upload/sample.png");

    act(() => {
      root.unmount();
    });
  });

  it("shows unsafe or local URLs as text instead of clickable external links", () => {
    const root = createRoot(container);

    act(() => {
      root.render(
        <IssueWorkProductsSection
          workProducts={[
            createWorkProduct({
              url: "file:///tmp/paperclip/output.png",
              provider: "paperclip",
              type: "artifact",
              title: "Local output",
            }),
          ]}
        />,
      );
    });

    expect(container.textContent).toContain("file:///tmp/paperclip/output.png");
    expect(container.querySelector("a[data-testid='issue-work-product']")).toBeNull();
    expect(container.querySelector("div[data-testid='issue-work-product']")).not.toBeNull();

    act(() => {
      root.unmount();
    });
  });
});
